# Use official Go image
FROM golang:1.23.1-alpine

WORKDIR /app

# Install Air for live reloading

RUN go install github.com/air-verse/air@latest
# Copy Go module files and download dependencies
COPY ../go.mod ../go.sum ./
RUN go mod download

# Copy application source code
COPY . .

# Expose the application port
EXPOSE 8080

WORKDIR /app/kgs

# Start the application with Air
CMD ["air"]
