# Use the official PostgreSQL image
FROM postgres:14

# Set environment variables
ENV POSTGRES_USER=admin
ENV POSTGRES_PASSWORD=admin
ENV POSTGRES_DB=url_shortener

# Expose PostgreSQL default port
EXPOSE 5432
